### ISSUE TITLE
Request: Enable localhost as callback URL (allows external browser usage)

### ISSUE THREAD

**Issue by mica-alex** [HyCraftHD/Minecraft-Authenticator#1]
Hello,

I have had great success so far with this library, and look forward to ~~implementing~~releasing(edit: because I already have things implemented in my dev branch) it in my custom launcher. There is currently one limitation holding me back, which is that my launcher's GUI is in JavaFX, and the JavaFX WebView has problems with the Microsoft login. 

As a solution, I've created a process in my application where it launches the system web browser to the URL, and creates and HTTP listener on localhost for callback. Everything works great when I tested using my own client ID (though of course I cannot use that auth code for the minecraft_authenticator library). When I use the URL from `MicrosoftService.oAuthLoginUrl()` and replace the redirect URI with `MicrosoftService.oAuthLoginUrl().toString().replaceAll(
                        Constants.MICROSOFT_OAUTH_REDIRECT_URL, "http://localhost" )`, the following message is shown from Microsoft when the page loads:

```
We're unable to complete your request
invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.
```

Can the "http://localhost" redirect URL please be enabled for the library?

![image](https://user-images.githubusercontent.com/83238954/120717318-57f86580-c495-11eb-8e23-1bfece20d317.png)

**Comment by mica-alex** [comment]
Greetings,

After examining the code, I now see that this library uses the native Minecraft client ID, thus you likely don't have control over the Azure OAuth app. I will work around this

**Comment by HyCraftHD** [comment]
Hello, yes as the minecraft launcher client id only allows ``https://login.live.com/oauth20_desktop.srf`` as redirect url it cannot be changed.
I'll see if I can add a mode with a custom azure application.

The WebView JavaFX is probably bugging because of a missing CookieManager. Have you added one?

**Comment by HyCraftHD** [comment]
I'll repopen to remind me

**Comment by mica-alex** [comment]
Thank you for getting back to me. 

You got it, it was the cookie manager.  I must’ve misinterpreted the page I read on the web view cookie management, because I didn’t think that was required. Works perfectly now!

As far as adding support via a custom Azure application, I think that would be awesome. All I had needed to do aside from setting up the custom Azure application was open the system browser with ‘System.open(“https://login.live.com…../?redirectUri=http://localhost:[RandomPort]”)’ and then made a simple HTTP server on that random port in my app to listen to the callback/redirect.

**Comment by HyCraftHD** [comment]
1.0.1 addes the support for custom azure applications.
Thanks for the suggestion.

**Comment by HyCraftHD** [comment]
Here is a basic reference implementation https://github.com/HyCraftHD/Minecraft-Authenticator/blob/main/src/test/java/net/hycrafthd/minecraft_authenticator/test/CustomAzureApplicationMain.java
