### ISSUE TITLE
Microsoft login with username and password

### ISSUE THREAD

**Issue by 1RandomDev** [HyCraftHD/Minecraft-Authenticator#2]
Would be great for automating things like bots that connect without any user interaction if I could provide a username + password instead of OAuth. (At least when 2FA is off)

**Comment by HyCraftHD** [comment]
Microsoft does not allow that as far as i know

**Comment by 1RandomDev** [comment]
Don't know/care if it's allowed, but the [MCAuthLib](https://github.com/GeyserMC/MCAuthLib) and the [node-minecraft-protocol](https://github.com/PrismarineJS/node-minecraft-protocol) libraries are able to do so. Couldn't that be implemented to this library?

And if I decide to use OAuth, will the token last forever if I don't logout or what so ever or is manual intervention required occasionally. For my use case it has to be 100% reliable.

**Comment by HyCraftHD** [comment]
`Don't know/care if it's allowed, but the [MCAuthLib](https://github.com/GeyserMC/MCAuthLib) and the [node-minecraft-protocol](https://github.com/PrismarineJS/node-minecraft-protocol) libraries are able to do so. Couldn't that be implemented to this library?`

Probably not, as it contains some interesting hacks that may break at any time: (https://github.com/GeyserMC/MCAuthLib/blob/3be04be9f1e659e91aec540c2f099266fe0a2aa5/src/main/java/com/github/steveice10/mc/auth/service/MsaAuthenticationService.java#L106-L198)
It's probably the best to implement this logic your self or just use the linked library.

``And if I decide to use OAuth, will the token last forever if I don't logout or what so ever or is manual intervention required occasionally. For my use case it has to be 100% reliable.``

Yes, the refresh token is persistent as long as it is not revoked, e.g. when changing passwords, etc.

**Comment by 1RandomDev** [comment]
> Yes, the refresh token is persistent as long as it is not revoked, e.g. when changing passwords, etc.

Ok think it's better to use the official way
