### ISSUE TITLE
[NOT AN ISSUE] How to use this with Eclipse IDE

### ISSUE THREAD

**Issue by 0rangy** [HyCraftHD/Minecraft-Authenticator#5]
I just want to use the code snippet provided in the readme file but how do I import it in a regularjava project please send help.

**Comment by HyCraftHD** [comment]
The simple way is to use gradle or maven (https://github.com/HyCraftHD/Minecraft-Authenticator#include-in-your-own-project)

Else you need to download the listed jars:
- https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
- https://repo.u-team.info/net/hycrafthd/minecraft_authenticator/3.0.2/minecraft_authenticator-3.0.2.jar

and add them to the eclipse external jars.

**Comment by 0rangy** [comment]
Thank you so much!
